import type { SemanticBlockType } from "../types"

export const SEMANTIC_ALIASES: Record<SemanticBlockType, string[]> = {
  definition: [
    "definition",
    "description",
    "meaning",
    "overview",
    "explanation",
    "intro",
    "introduction",
    "about",
    "what-is",
    "what",
    "concept-overview",
  ],
  concept: [
    "concept",
    "concepts",
    "key-point",
    "key-points",
    "important-point",
    "important-points",
    "principles",
    "features",
    "characteristics",
    "ideas",
    "fundamentals",
    "highlights",
    "core",
  ],
  code: [
    "code",
    "snippet",
    "example-code",
    "sample-code",
    "implementation",
    "syntax",
    "program",
    "source",
    "script",
    "example",
  ],
  summary: [
    "summary",
    "recap",
    "takeaways",
    "key-takeaways",
    "highlights",
    "revision",
    "quick-review",
    "conclusion",
  ],
  warning: [
    "warning",
    "warnings",
    "pitfall",
    "pitfalls",
    "mistake",
    "mistakes",
    "caution",
    "avoid",
    "things-to-avoid",
    "common-errors",
    "gotchas",
  ],
  memory: [
    "memory",
    "mnemonic",
    "remember",
    "memory-trick",
    "tip-to-remember",
    "key-phrase",
  ],
  related: [
    "related",
    "related-topics",
    "see-also",
    "references",
    "connections",
    "links",
  ],
  interview: [
    "interview",
    "interview-tip",
    "interview-question",
    "interview-questions",
    "question",
    "questions",
    "faq",
    "common-questions",
  ],
  note: [
    "note",
    "notes",
    "extra",
    "additional",
    "remarks",
    "additional-notes",
    "comment",
  ],
  generic: [],
}

export const TITLE_ALIASES = ["title", "topic", "subject", "heading", "name", "header"]
export const SUBTITLE_ALIASES = ["subtitle", "tagline", "subheading", "context", "description-short"]
